env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://www.activist.org/en/
    - https://www.activist.org/
  parameters:
    failOnError: true
    progressToStdout: true
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 10
    url: https://www.activist.org/
  type: spider
- parameters:
    maxDuration: 10
    url: https://www.activist.org/
  type: spiderAjax
- parameters:
    maxDuration: 60
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: IGNORE
    customMessage: Cross-Domain Misconfiguration
    id: 10016
  - action: IGNORE
    customMessage: X-Frame-Options Header
    id: 10020
  - action: IGNORE
    customMessage: X-Content-Type-Options Header
    id: 10021
  - action: IGNORE
    customMessage: Content Security Policy (CSP) Header Not Set
    id: 10038
  - action: IGNORE
    customMessage: Permissions Policy Header
    id: 10063
  - action: IGNORE
    customMessage: Application Error Disclosure
    id: 90022
  - action: IGNORE
    customMessage: Non-Storable Content
    id: 10049
  - action: IGNORE
    customMessage: Modern Web Application
    id: 10109
  - action: IGNORE
    customMessage: Timestamp Disclosure
    id: 10096
  - action: IGNORE
    customMessage: CSP Scanner
    id: 10055
  - action: IGNORE
    customMessage: .htaccess Information Leak
    id: 40032
  - action: IGNORE
    customMessage: Private IP Disclosure
    id: 2
  - action: IGNORE
    customMessage: Absence of Anti-CSRF Tokens
    id: 10202
  - action: IGNORE
    customMessage: User Agent Fuzzer
    id: 10104
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/reports/zap-baseline-scan-2025-04-03-173015.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
