name: OWASP ZAP Optimized Security Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Run weekly on Mondays at 2 AM UTC

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Security Scan with OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.activist.org/en/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -S -T 60 -m 10 -z "-config scanner.attackStrength=HIGH -config scanner.alertThreshold=MEDIUM"'
          issue_title: 'OWASP ZAP Security Report'
          fail_action: false
          allow_issue_writing: true
